version: '2'

services:
  node0:
    container_name: node0
    image: ubuntu:16.04
    ports:
    - "26656-26657:26656-26657"
    volumes:
    - ./build:/home
    command: '/bin/bash'
    tty: true
    stdin_open: true
    networks:
      localnet:
        ipv4_address: 192.168.20.2

  node1:
    container_name: node1
    image: ubuntu:16.04
    ports:
    - "26659-26660:26656-26657"
    volumes:
    - ./build:/home
    command: '/bin/bash'
    tty: true
    stdin_open: true
    networks:
      localnet:
        ipv4_address: 192.168.20.3

  node2:
    container_name: node2
    image: ubuntu:16.04
    ports:
    - "26661-26662:26656-26657"
    volumes:
    - ./build:/home
    command: '/bin/bash'
    tty: true
    stdin_open: true
    networks:
      localnet:
        ipv4_address: 192.168.20.4

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.20.0/16
