version: '2'

services:
  node0:
    container_name: node0
    image: ubuntu:16.04
    ports:
    - "26656-26657:26656-26657"
    - "8545:8545"
    volumes:
    - ./build:/home
    command: /bin/bash -c 'cd /home/ && ./halled start --home node0 --log_level info --rpc.unsafe --rpc.laddr "tcp://0.0.0.0:26657"'
    networks:
      localnet:
        ipv4_address: 192.168.20.2

  node1:
    container_name: node1
    image: ubuntu:16.04
    ports:
    - "26011-26012:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/bash -c 'cd /home/ && ./halled start --home node1 --log_level info --rpc.unsafe'
    networks:
      localnet:
        ipv4_address: 192.168.20.3

  node2:
    container_name: node2
    image: ubuntu:16.04
    ports:
    - "26021-26022:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/bash -c 'cd /home/ && ./halled start --home node2 --log_level info --rpc.unsafe'
    networks:
      localnet:
        ipv4_address: 192.168.20.4
  node3:
    container_name: node3
    image: ubuntu:16.04
    ports:
    - "26031-26032:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/bash -c 'cd /home/ && ./halled start --home node3 --log_level info --rpc.unsafe'
    networks:
      localnet:
        ipv4_address: 192.168.20.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.20.0/16
