version: '3'

services:
  node0:
    container_name: node0
    image: ubuntu:16.04
    ports:
    - "26001-26002:26656-26657"
    volumes:
    - ./build:/home
    environment:
      - ID=0
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh node0"
    networks:
      localnet:
        ipv4_address: 192.168.20.2
  node1:
    container_name: node1
    image: ubuntu:16.04
    ports:
    - "26011-26012:26656-26657"
    volumes:
    - ./build:/home
    environment:
      - ID=1
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh  node1"
    networks:
      localnet:
        ipv4_address: 192.168.20.3
  node2:
    container_name: node2
    image: ubuntu:16.04
    ports:
    - "26021-26022:26656-26657"
    volumes:
    - ./build:/home
    environment:
      - ID=2
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh node2"
    networks:
      localnet:
        ipv4_address: 192.168.20.4
  node3:
    container_name: node3
    image: ubuntu:16.04
    ports:
    - "26031-26032:26656-26657"
    volumes:
    - ./build:/home
    environment:
      - ID=3
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh node3"
    networks:
      localnet:
        ipv4_address: 192.168.20.5
  node4:
    container_name: node4
    image: ubuntu:16.04
    ports:
    - "26041-26042:26656-26657"
    volumes:
    - ./build:/home
    environment:
      - ID=4
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh node4"
    networks:
      localnet:
        ipv4_address: 192.168.20.6
  node5:
    container_name: node5
    image: ubuntu:16.04
    ports:
    - "26051-26052:26656-26657"
    volumes:
    - ./build:/home
    environment:
      - ID=5
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh node5"
    networks:
      localnet:
        ipv4_address: 192.168.20.7
  node6:
    container_name: node6
    image: ubuntu:16.04
    ports:
    - "26061-26062:26656-26657"
    volumes:
    - ./build:/home
    environment:
      - ID=6
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh node6"
    networks:
      localnet:
        ipv4_address: 192.168.20.8
  node7:
    container_name: node7
    image: ubuntu:16.04
    ports:
    - "26071-26072:26656-26657"
    volumes:
    - ./build:/home
    environment:
      - ID=7
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh node7"
    networks:
      localnet:
        ipv4_address: 192.168.20.9
  node8:
    container_name: node8
    image: ubuntu:16.04
    ports:
    - "26081-26082:26656-26657"
    volumes:
    - ./build:/home
    environment:
      - ID=8
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh node8"
    networks:
      localnet:
        ipv4_address: 192.168.20.10
  node9:
    container_name: node9
    image: ubuntu:16.04
    ports:
    - "26091-26092:26656-26657"
    volumes:
    - ./build:/home
    environment:
      - ID=9
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh node9"
    networks:
      localnet:
        ipv4_address: 192.168.20.11
  node10:
    container_name: node10
    image: ubuntu:16.04
    ports:
    - "26656-26657:26656-26657"
    - "8545:8545"
    volumes:
    - ./build:/home
    environment:
      - ID=10
      - LOG=${LOG:-halled.log}
    entrypoint: "bash start.sh node10"
    networks:
      localnet:
        ipv4_address: 192.168.20.12

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.20.0/24
