version: '3.2'

services:
  node0:
    image: halledwade/halled:v0.1.4
    ports:
    - target: 26656
      published: 26656
      protocol: tcp
      mode: host
    - target: 26657
      published: 26657
      protocol: tcp
      mode: host
    - target: 8545
      published: 8545
      protocol: tcp
      mode: host
    volumes:
    - /root/.halled:/root/.halled
    - /root/.hallecli:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == node0
  node1:
    image: halledwade/halled:v0.1.4
    ports:
    - target: 26656
      published: 26656
      protocol: tcp
      mode: host
    - target: 26657
      published: 26657
      protocol: tcp
      mode: host
    volumes:
    - /root/.halled:/root/.halled
    - /root/.hallecli:/root/.hallecli
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == node1
  node2:
    image: halledwade/halled:v0.1.4
    ports:
    - target: 26656
      published: 26656
      protocol: tcp
      mode: host
    - target: 26657
      published: 26657
      protocol: tcp
      mode: host
    volumes:
    - /root/.halled:/root/.halled
    - /root/.hallecli:/root/.hallecli
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == node2
  node3:
    image:  halledwade/halled:v0.1.4
    ports:
    - target: 26656
      published: 26656
      protocol: tcp
      mode: host
    - target: 26657
      published: 26657
      protocol: tcp
      mode: host
    volumes:
    - /root/.halled:/root/.halled
    - /root/.hallecli:/root/.hallecli
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == node3
  node4:
    image:  halledwade/halled:v0.1.4
    ports:
    - target: 26656
      published: 26656
      protocol: tcp
      mode: host
    - target: 26657
      published: 26657
      protocol: tcp
      mode: host
    volumes:
    - /root/.halled:/root/.halled
    - /root/.hallecli:/root/.hallecli
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == node4
  node5:
    image:  halledwade/halled:v0.1.4
    ports:
    - target: 26656
      published: 26656
      protocol: tcp
      mode: host
    - target: 26657
      published: 26657
      protocol: tcp
      mode: host
    volumes:
    - /root/.halled:/root/.halled
    - /root/.hallecli:/root/.hallecli
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == node5
  node6:
    image:  halledwade/halled:v0.1.4
    ports:
    - target: 26656
      published: 26656
      protocol: tcp
      mode: host
    - target: 26657
      published: 26657
      protocol: tcp
      mode: host
    volumes:
    - /root/.halled:/root/.halled
    - /root/.hallecli:/root/.hallecli
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == node6
