version: '3'

services:
  node0:
    container_name: node0
    image: halledwade/halled:v0.1.4
    ports:
    - "26001-26002:26656-26657"
    volumes:
    - ./build/node0:/root/.halled
    - ./build/clicfg:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.2
  node1:
    container_name: node1
    image: halledwade/halled:v0.1.4
    ports:
    - "26011-26012:26656-26657"
    volumes:
    - ./build/node1:/root/.halled
    - ./build/clicfg:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.3
  node2:
    container_name: node2
    image: halledwade/halled:v0.1.4
    ports:
    - "26021-26022:26656-26657"
    volumes:
    - ./build/node2:/root/.halled
    - ./build/clicfg:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.4
  node3:
    container_name: node3
    image: halledwade/halled:v0.1.4
    ports:
    - "26031-26032:26656-26657"
    volumes:
    - ./build/node3:/root/.halled
    - ./build/clicfg:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.5
  node4:
    container_name: node4
    image: halledwade/halled:v0.1.4
    ports:
    - "26041-26042:26656-26657"
    volumes:
    - ./build/node4:/root/.halled
    - ./build/clicfg:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.6
  node5:
    container_name: node5
    image: halledwade/halled:v0.1.4
    ports:
    - "26051-26052:26656-26657"
    volumes:
    - ./build/node5:/root/.halled
    - ./build/clicfg:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.7
  node6:
    container_name: node6
    image: halledwade/halled:v0.1.4
    ports:
    - "26061-26062:26656-26657"
    volumes:
    - ./build/node6:/root/.halled
    - ./build/clicfg:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.8
  node7:
    container_name: node7
    image: halledwade/halled:v0.1.4
    ports:
    - "26071-26072:26656-26657"
    volumes:
    - ./build/node7:/root/.halled
    - ./build/clicfg:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.9
  node8:
    container_name: node8
    image: halledwade/halled:v0.1.4
    ports:
    - "26081-26082:26656-26657"
    volumes:
    - ./build/node8:/root/.halled
    - ./build/clicfg:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.10
  node9:
    container_name: node9
    image: halledwade/halled:v0.1.4
    ports:
    - "26091-26092:26656-26657"
    volumes:
    - ./build/node9:/root/.halled
    - ./build/clicfg:/root/.hallecli
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.11
  node10:
    container_name: node10
    image: halledwade/halled:v0.1.4
    ports:
    - "26656-26657:26656-26657"
    - "8545:8545"
    volumes:
    - ./build/node10:/root/.halled
    - ./build/clicfg:/root/.hallecli
    environment:
      - ID=10
      - LOG=${LOG:-halled.log}
    command: halled start  --minimum-gas-prices  5.0uhale  --pruning=nothing  --log_level "main:info,state:info,mempool:info"   --rpc.laddr "tcp://0.0.0.0:26657"
    networks:
      localnet:
        ipv4_address: 192.168.20.12

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.20.0/24
